REM INSERTING into "users"
SET DEFINE OFF;
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('1','1','MIDEBEL Rondouba Rodrigue','U202101','admin2021','66484220','rodrigue.midbel@gmail.com','Secteur 24','1','0',to_timestamp('08/04/22 14:23:19,173000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,173000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('2','1','NIKIEMA Laurent','U202102','admin','77505873','lnikiema@gmail.com','Samandin','1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('3','1','TOPAN Zakaria','U202103','admin','76403214','ztopan@logo_services.com','Somgandé, secteur 13','1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('4','5','SAWADOGO karim','sawadogo.karim','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('5','5','KOUGWINDEGA DRAMANE','kougwindega.dramane','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('6','3','ZIGANI Théodore','zigani.theodore','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('7','4','DIALLO Abdramane','diallo.abdramane','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('8','5','LOMPO Léa Claudine','lompo.lea','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,174000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('9','5','TRAORE STephanie','traore.stephanie','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('10','5','ZONGO Idrissa','zongo.idrissa','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('11','5','LAMIZANA Salif','lamizana.salif','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('12','5','TIENDREBEOGO Wend Kuni Viviane','tiendrebeogo.viviane','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('13','5','SAVADOGO Raissa','savadogo.raissa','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('14','5','ZONGO Souleymane','zongo.souleymane','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('15','5','GOUBA Benjamin','gouba.benjamin','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('16','5','ZONGO Sayouba','zongo.sayouba','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('17','2','DPMP','DPMP','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('18','5','NADIE Abzeta','nadie.abzeta','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('19','5','DIANDA Martine','dianda.martine','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,175000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('20','5','TRAORE Amidou','traore.amidou','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,176000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,176000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('21','5','TINTO Issoufou','tinto.issoufou','SONABEL2020',null,null,null,'1','0',to_timestamp('08/04/22 14:23:19,176000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('08/04/22 14:23:19,176000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "users" ("id","usergroup_id","name","username","password","telephone","email","adresse","statut","isconnected","created_at","updated_at") values ('22','5','YAMEOGO Georges','yameogo.georges','SONABEL2020',null,null,null,'1',null,to_timestamp('14/04/22 11:51:56,075000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('14/04/22 11:51:56,075000000','DD/MM/RR HH24:MI:SSXFF'));
commit;

REM INSERTING into "planitems"
SET DEFINE OFF;
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('1','1','1','Fonds Propres Investissement','A','234220','A','32000',null,'DT','DTME','99000000','Sectionneur','99000000','Acquisition de sectionneurs (34,5kV et 225kV) et transformateur 225 kV',null,'AOO ','3','6','10/02/22','21/02/22',null,'23/03/22',null,'6',null,null,null,null,'07/03/22',null,'180',null,'03/11/22',null,null,null,null,to_timestamp('13/03/22 16:08:05,456000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:05,456000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('2','2','1','Fonds Propres Investissement','A','234220','A','45000',null,'DD / DCC','DD - DCC','2571394000','Restructuration du réseau HTA/BTA / DRCO','2571394000','Acquisition de matériels pour restructuration de réseaux et création des postes dans les Directions Régionales (Fourniture et travaux)',null,'AOOI ','8','2','10/02/22','21/02/22',null,'07/04/22',null,'12',null,null,null,null,'22/05/22',null,'210',null,'18/12/22',null,null,null,null,to_timestamp('13/03/22 16:08:05,440000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:05,440000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('3','3','1','Fonds Propres Investissement','I','213100','I','20000',null,'DEPI','DEPI','22500000','Logiciels','22500000','Mise à jour du Modèle financier',null,'DPA',null,'9','10/02/22','14/02/22',null,'16/03/22',null,'16',null,null,null,null,'15/05/22',null,'180',null,'44876',null,null,null,null,to_timestamp('13/03/22 16:08:05,487000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:05,487000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('4','4','1','Fonds Propres Exploitation','Budget. Exp.','604110','Budget. Exp.','82000',null,'DGA / DMP','DMP','108435000',null,'108435000','Achats de compteurs à pré-paiement triphasés',null,'AOO',null,'6','10/02/22',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('13/03/22 16:08:35,149000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:35,149000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('5','5','1','Fonds Propres Exploitation','Budget. Exp.','604440','Budget. Exp.','53000',null,'DPTCE / DP','DP','63000000',null,'63000000','Depannage moteur MTU DORI',null,'DPX',null,'12','10/02/22',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('13/03/22 16:08:35,242000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:35,242000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('6','6','1','Fonds Propres Exploitation','Budget. Exp.','604440','Budget. Exp.','52210',null,'DPTCE / DP','DP','198363800',null,'198363800','Révision général G3 (MITSUBISHI) / DORI et Révision d''atellage G2 (KTA) / DORI',null,'AOO',null,'1','10/02/22',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('13/03/22 16:08:35,274000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:35,274000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('7','7','1','Fonds Propres Exploitation','Budget. Exp.','604710','Budget. Exp.','81000',null,'DAGP / DMP','DMP','237090000',null,'237090000','Achats Fournitures Informatiques',null,'AOO',null,'6','10/02/22',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_timestamp('13/03/22 16:08:35,289000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:35,289000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('8','8','1','Financement externe','Fin. Ext.',null,'Fin. Ext.','46000','PDCEL','DRO','DCC','308327000',null,'308327000','Travaux d''extensions de réseau à Batié, Dano, Diebougou et Gaoua',null,'AOO','4','5','10/02/22','28/12/21',null,'27/01/22',null,'6',null,null,null,null,'10/07/22',null,'540',null,'01/01/24',null,null,null,null,to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('9','9','1','Financement externe','Fin. Ext.',null,'Fin. Ext.','45000','PDCEL.','DRCO','DCC','1031381000',null,'1031381000','Travaux d''extensions de réseau à Boromo, Dédougou, Koudougou, Léo, Nouna, Réo et Sapouy',null,'AOO','7','10','10/02/22','28/12/21',null,'27/01/22',null,'12',null,null,null,null,'10/07/22',null,'540',null,'01/01/24',null,null,null,null,to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into "planitems" ("id","num_ordre","plan_id","budget","typcredit","immobilisation","credit","centre_cout","projet","localisation","responsable","montant_estime","composante","montant_dispo","designation","type","mode","nbr_lot","agent_id","date_tech","date_dgcmef","date_dgcmef_reel","date_off","date_off_reel","temp","temp_reel","date_resultat","resultat","date_visite_site","date_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_butoir","date_reel_fin","budget_travaux","observation","statut","created_at","updated_at") values ('10','10','1','Financement externe','Fin. Ext.',null,'Fin. Ext.','44000','.PDCEL','DRCE','DCC','366753000',null,'366753000','Travaux d''extensions de réseau à Boulsa, Koupela, Tenkodogo et Zorgho ',null,'AOO','4','2','10/02/22','28/12/21',null,'27/01/22',null,'16',null,null,null,null,'10/07/22',null,'540',null,'01/01/24',null,null,null,null,to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('13/03/22 16:08:54,615000000','DD/MM/RR HH24:MI:SSXFF'));
commit;



REM INSERTING into "privileges"
SET DEFINE OFF;
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('1','1','1','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('2','1','2','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('3','1','3','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('4','1','4','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('5','1','5','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('6','1','6','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('7','1','7','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('8','1','8','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('9','1','9','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('10','1','10','1','1','1','1',null,null,null,null);

Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('11','2','1','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('12','2','2','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('13','2','3','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('14','2','4','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('15','2','5','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('16','2','6','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('17','2','7','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('18','2','8','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('19','2','9','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('20','2','10','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('21','3','1','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('22','3','2','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('23','3','3','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('24','3','4','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('25','3','5','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('26','3','6','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('27','3','7','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('28','3','8','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('29','3','9','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('30','3','10','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('31','4','1','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('32','4','2','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('33','4','3','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('34','4','4','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('35','4','5','1','0','0','',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('36','4','6','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('37','4','7','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('38','4','8','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('39','4','9','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('40','4','10','1','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('41','5','1','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('42','5','2','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('43','5','3','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('44','5','4','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('45','5','5','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('46','5','6','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('47','5','7','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('48','5','8','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('49','5','9','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('50','5','10','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('51','6','1','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('52','6','2','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('53','6','3','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('54','6','4','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('55','6','5','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('56','6','6','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('57','6','7','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('58','6','8','0','0','0','0',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('59','6','9','1','1','1','1',null,null,null,null);
Insert into "privileges" ("id","usergroup_id","fonctionalite_id","view","add","edit","remove","created_by","modified_by","created_at","updated_at") values ('60','6','10','0','0','0','0',null,null,null,null);
commit;

REM INSERTING into SONABEL."ventes"
SET DEFINE OFF;
Insert into SONABEL."ventes" ("id","num_vente","lot_id","fournisseur_id","date_vente","heure_vente","montant","acheteur","contact_acheteur","statut","created_at","updated_at") values ('1','496579-2022','5','52','2022/10/09',null,'50000','Fatim TASSEMBEDO','78977879','Payé',to_timestamp('09/10/22 00:00:49,581000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:00:49,581000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into SONABEL."ventes" ("id","num_vente","lot_id","fournisseur_id","date_vente","heure_vente","montant","acheteur","contact_acheteur","statut","created_at","updated_at") values ('2','444336-2022','6','52','2022/10/09',null,'50000','Fatim TASSEMBEDO','78977879','Payé',to_timestamp('09/10/22 00:01:28,853000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:01:28,853000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into SONABEL."ventes" ("id","num_vente","lot_id","fournisseur_id","date_vente","heure_vente","montant","acheteur","contact_acheteur","statut","created_at","updated_at") values ('3','118805-2022','5','51','2022/10/09',null,'50000','Brice BELEM','74859632','Payé',to_timestamp('09/10/22 00:02:23,597000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:02:23,597000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into SONABEL."ventes" ("id","num_vente","lot_id","fournisseur_id","date_vente","heure_vente","montant","acheteur","contact_acheteur","statut","created_at","updated_at") values ('4','275269-2022','5','14','2022/10/09',null,'50000','Kadiadja OUEDRAOGO','65987412','Non payé',to_timestamp('09/10/22 00:03:13,649000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:03:13,649000000','DD/MM/RR HH24:MI:SSXFF'));
commit;

REM INSERTING into SONABEL."caisses"
SET DEFINE OFF;
Insert into SONABEL."caisses" ("id","num_recu","date_recu","vente_id","modepaiement_id","ref_virement","created_at","updated_at") values ('1','113538','2022/10/09','1','1','RAS',to_timestamp('09/10/22 00:11:37,814000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:11:37,814000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into SONABEL."caisses" ("id","num_recu","date_recu","vente_id","modepaiement_id","ref_virement","created_at","updated_at") values ('2','747121','2022/10/09','2','1','RAS',to_timestamp('09/10/22 00:12:15,070000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:12:15,070000000','DD/MM/RR HH24:MI:SSXFF'));
Insert into SONABEL."caisses" ("id","num_recu","date_recu","vente_id","modepaiement_id","ref_virement","created_at","updated_at") values ('3','327496','2022/10/09','3','1','RAS',to_timestamp('09/10/22 00:12:26,582000000','DD/MM/RR HH24:MI:SSXFF'),to_timestamp('09/10/22 00:12:26,582000000','DD/MM/RR HH24:MI:SSXFF'));
commit;

